#
# dc/firebase-tools/base.yml
#
# Base for using Firebase CLI, via Docker Compose.
#
services:
  base:
    #image: local_firebase_tools      # could use this to be able to extend the emulators Dockerfile from the CLI's, but... it's not a clear linkage. No thanks.
    build:
      context: .
      cache_from:
        - alpine:latest
      args:
        - FIREBASE_TOOLS_VERSION=11.2.0

      # 'ports', 'volumes', 'working_dir', 'command', 'profiles' to be provided by downstream
