apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitoring
data:
  prometheus.yml: |-
    #global:
    #  external_labels:
    #    x_origin: x
    remote_write:
    - url: ${GC_PUSH_URL}
      basic_auth:
        username: ${GC_USER}
        password: ${GC_API_KEY}
