#
# app/dc.cypress.yml
#
# Everything needed by 'npm test'
#
# Expects:
#   - 'PORT' to be defined. Used internally between Vite and Cypress.
#
name: 11567956
services:
  # Similar to what 'make dev' uses, but forwards the browser to 'emul-for-app' (via the different '.env**' file),
  # instead of 'localhost'.
  #
  # Both of them, however, use the same backend instance (which runs under DC 'app' namespace).
  #
  # Note:
  #   This service remains running after 'make test'. That may be intentional, since it reduces startup times.
  #
  #   tbd.
  #   On the other hand, having 'npm test' not leave trails around would be good, as well.
  #   IDEALLY, we'd be able to use the same 'vite-dev' for both "localhost" and here.
  #
  vite-dev-for-test:
    extends:
      file: dc.base.yml
      service: vite-base
      # uses 'PORT' parameter

    volumes:
      # --- RO
      - ../backend/firebase.app.js:/work/firebase.app.js:ro
      - ./tmp/.env.dev_test:/work/.env:ro
    environment:
      - MODE=local
    profiles: ['manual']

  # Cypress run
  #
  run_tests:
    build:
      context: tools/cypress.dc
      target: with_libs
    volumes:
      # --- RO
      - ./cypress:/work/cypress:ro
      - ./cypress.config.js:/work/cypress.config.js:ro
      - ./package.json:/work/package.json:ro
      - ./node_modules:/work/node_modules:ro
        #
      - ../backend/firebase.app.js:/work/firebase.app.js:ro
        # ^-- map to /work, so ESM scope covers it
      # --- output
      - ./.screenshots:/work/.screenshots:delegated
    environment:
      - CYPRESS_defaultCommandTimeout=10000
      - CYPRESS_baseUrl=http://vite-dev-for-test:${PORT}
      - FIREBASE_APP_JS=/work/firebase.app.js
      - EMUL_HOST=emul-for-app
    working_dir: /work
    command: sh -c '
      cypress run
      '
    profiles: ['manual']

    networks:
      - default   # vite-dev-for-test
      - george    # emul-for-app

    depends_on:
      vite-dev-for-test:
        condition: service_healthy

  # Check version (DEBUG)
  #
  check_ver:
    build:
      context: tools/cypress.dc
    command: |
      cypress version
    profiles: ['manual']

networks:
  george:
    name: app_default
    external: true
