#
# app/docker-compose.prod.build.ci.yml
#
# Building for CI.
#
services:
  #
  # Expects:
  #   - RELEASE
  #   #- SECRET_SAMPLE (optional)   # for #later...
  #
  build:
    build:
      context: tools/vite.dc
    volumes:
      # --- RO
      - ./node_modules:/work/node_modules:ro
      - ./vite.config.js:/work/vite.config.js:ro
      - ./rollup.chunks.js:/work/rollup.chunks.js:ro
      - ./${FIREBASE_CONFIG_JSON:-firebase.config.json}:/work/firebase.config.json:ro
      # --- Sources
      - ./src:/work/src:ro
      - ./prod:/work/prod:ro
      - ./public:/work/public:ro
      # --- Output
      - ./dist:/work/dist:delegated
      # --- other
      - ../../../branding/favicon.png/:/work/public/favicon.png:ro
    command: sh -c '
      echo "VITE_RELEASE=${RELEASE}" >> .env &&

      vite build
      '
      #([ -z "${SECRET_SAMPLE:-}" ] || echo "VITE_SECRET_SAMPLE=${SECRET_SAMPLE:-}" >> .env) &&
    environment:
      - VITE_VISUALIZER=false
    profiles: ['manual']
