#
# docker-compose.ci.yml
#
# An override for Cloud Build
#
# Expects:
#   - PORT to declare the port to show UI in
#   - to be launched with '-f' of also 'docker-compose.local.yml' (overlays on it, without 'extends')
#
# To debug locally:
#   - temporarily comment out the 'network_mode' and 'container_name' fields.
#
# References:
#   - Share Compose configurations between files and projects (Docker Compose docs)
#     -> https://docs.docker.com/compose/extends/
#
services:

  # Note: The implementation is /very/ similar to 'docker-compose.local.yml' (essentially the same, without
  #     'profiles: ["manual"]'), but decided to keep them unrelated (no chain of three '-f's).
  #
  #     Also: no "profile: ['manual']" here, since we run the service up.
  #
  # NOTE!!! Trying to use a different port _within_ the DC than that exposed did not work (browser ends up in a
  #     weird confused state). No harm in keeping them the same.
  #
  vite-dev:
    network_mode: cloudbuild
    container_name: vite
      # The domain node name (not 'localhost'!) to use for the front end, e.g. 'http://vite:3000'

    healthcheck:
      test: "nc -z localhost $PORT"
      interval: 0.9s
      start_period: 20s

  # Make sure Vite is launched.
  #
  vite-for-ci-launched:
    image: node:16-alpine
    command: sh -c true
    depends_on:
      vite-dev:
        condition: service_healthy
    profiles: ['manual']
