#
# app/docker-compose.online.yml
#
# Overlay, for 'npm run dev:online' specificity.
#
# Environment variables:
#   - ENV (default: 'staging'); the staging environment to work against.
#
# Intentions:
#   - Host the front end files with a cloud backend, according to 'ENV' env.var.
#
services:
  vite-online:
    extends:
      file: docker-compose.base.yml
      service: vite-base

    volumes:
      #--- RO
      - ./tools/gen-vite-env-online.js:/work/tools/gen-vite-env-online.js:ro
      - ../../firebase.${ENV:-staging}.js:/work/firebase.js:ro
    environment:
      - MODE=online
      - ENV
    profiles: ['manual']
