#
# app/docker-compose.local.yml
#
# Expects:
#   PORT
#   PROJECT_ID
#
# Overlay, for 'npm run dev:local' specificity.
#
name: ffd37ba4
services:
  vite-dev:
    extends:
      file: dc.base.yml
      service: vite-base
    ports:
      - "$PORT:$PORT"

    volumes:
      # --- RO
      #- ../backend/firebase.app.js:/work/firebase.app.js:ro
      - ./tmp/.env.dev_local:/work/.env:ro
    command: sh -c '
      echo "{ \"projectId\":\"$PROJECT_ID\" }" > firebase.config.json &&

      vite --mode dev_local &&
        true
      '
      # Note: '&& true' somehow makes Ctrl-C work; keep it
    profiles: ['manual']

  # See that we see 'emul-for-app'
  #|debug:    # DEBUG
  #|  image: node:16-alpine
  #|  command: sh -c '
  #|    nc -z emul-for-app 6768 && echo "6768 ok" &&
  #|    nc -z emul-for-app 5003 && echo "5003 ok" &&
  #|    nc -z emul-for-app 6869 && echo "6869 ok" &&
  #|    nc -z emul-for-app 9101 && echo "9101 ok"
  #|    '
  #|  profiles: ['manual']

  #---
  # This is normally not needed, but CAN BECOME USEFUL if 'main.js' doesn't launch 'app.js' properly, to debug.
  #
  # Used via 'npm run _build:dev'
  #
  # tbd. Undocumented; broken. Fix. May be useful!
  #
#|  build:
#|    extends:
#|      file: dc.base.yml
#|      service: vite-base
#|
#|    volumes:
#|      # --- RO
#|      - ./tools/gen-vite-env-local.js:/work/tools/gen-vite-env-local.js:ro
#|      - ./.env.dev_local:/work/.env.local:ro
#|    command: sh -c
#|      'npm config set update-notifier false &&
#|
#|      npm install -g rollup-plugin-visualizer &&
#|      (cd / && mkdir node_modules && cd node_modules && ln -s $$NODE_PATH/rollup-plugin-visualizer .) &&
#|
#|      ([ -z "${SENTRY_SAMPLE_RATE:-}" ] || echo "VITE_SENTRY_SAMPLE_RATE=${SENTRY_SAMPLE_RATE:---}" >> .env) &&
#|
#|      vite build --mode dev_local
#|      '
#|    environment:
#|      - MODE=local
#|    profiles: ['manual']
