#
# app/docker-compose.local.yml
#
# Overlay, for 'npm run dev:local' specificity.
#
services:
  vite-dev:
    volumes:
      # --- RO
      - ./tools/gen-vite-env-local.js:/work/tools/gen-vite-env-local.js:ro
      - ../backend/firebase.app.json:/work/firebase.json:ro
    environment:
      - MODE=local
    profiles: ['manual']
