#
# app/docker-compose.prod.build.yml
#
name: 35bf1944
services:
  #---
  # Build production variant (manually, or 'first'; CI has a separate definition)
  #
  # Expects:
  #   - ENV
  #
  build:
    build:
      context: tools/vite.dc
    volumes:
      # --- RO
      - ./node_modules:/work/node_modules:ro         # note: should not have 'esbuild' in it
      - ./vite.config.js:/work/vite.config.js:ro     # Vite needs a restart to see config changes, thus 'ro'.
      - ./rollup.chunks.js:/work/rollup.chunks.js:ro
      - ./src:/work/src:ro
      - ./prod:/work/prod:ro
      - ./public:/work/public:ro
      - ./tmp/firebase.${ENV:-staging}.config.json:/work/firebase.config.json:ro
      - ./tmp/.env.${ENV:-staging}:/work/.env:ro
      # --- Output
      - ./dist:/work/dist:delegated
      - ./stats.html:/work/stats.html:delegated
      # --- other
      - ../../../branding/favicon.png/:/work/public/favicon.png:ro
      - ./tmp/.vite:/work/tmp/.vite:delegated    # persistence between runs
    command: sh -c '
      vite build
      '

    #environment:
      #- ENV     # e.g. "staging"
    profiles: ['manual']
