#
# app/docker-compose.online.yml
#
# Overlay, for 'npm run dev:online' specificity.
#
# Environment variables:
#   - ENV (default: 'staging'); the staging environment to work against.
#
# Intentions:
#   - Host the front end files with a cloud backend, according to 'ENV' env.var.
#
services:
  vite-dev:
    ports:
      - "3001:3001"     # wasn't able to have "$PORT:$PORT" here, in 'docker-compose.yml'
    volumes:
      #--- RO
      - ./tools/gen-vite-env-online.js:/work/tools/gen-vite-env-online.js:ro
      - ../../firebase.${ENV:-staging}.js:/work/firebase.js:ro
    environment:
      - SENTRY_DNS
      - PORT=3001
      - MODE=online
      - ENV

  #REMOVE???
  # Make sure Vite is launched.
  #
  #|vite-3001-launched:
  #|  image: node:16-alpine
  #|  command: sh -c true
  #|  depends_on:
  #|    vite-3001:
  #|      condition: service_healthy
