#
# app/docker-compose.test.yml
#
# Overlay, for 'npm test' speificity.
#
# Expects:
#   PORT with a number to a free port (e.g. 3002)
#
# Intentions:
#   Host and hot-module-reload the front end, for "npm test".
#   Unlike 'dev:local', no priming is needed. Cypress tests take care of it.
#
services:
  vite-for-test:
    extends:
      file: docker-compose.local.yml
      service: vite-dev

    command: sh -c
      'npm config set update-notifier false &&
      [ ! -d node_modules/esbuild ] || (echo >&2 ERROR:\ please remove 'node_modules/esbuild*'; false) &&

      npm run dc:launch:test
      '
    environment:
    #  - SENTRY_DSN
      - PORT=$PORT

    healthcheck:
      test: "nc -z localhost $PORT"
      interval: 0.9s
      start_period: 25s

  # Make sure Vite is launched. Used by 'npm test'.
  #
  vite-for-test-launched:
    image: node:16-alpine
    command: sh -c true
    depends_on:
      vite-for-test:
        condition: service_healthy
    profiles: ['manual']
