#
# app/docker-compose.online.yml
#
# Environment variables:
#   - ENV (default: 'staging'); the staging environment to work against.
#
# Intentions:
#   - Host the front end files with a cloud backend, according to 'ENV' env.var.
#
name: 245e80f4
services:
  vite-online:
    extends:
      file: dc.base.yml
      service: vite-base
    ports:
      - "$PORT:$PORT"

    volumes:
      #--- RO
      #- ../../firebase.${ENV:-staging}.js:/work/firebase.js:ro
      - ./tmp/.env.dev.${ENV:-staging}:/work/.env:ro
    environment:
      - MODE=online
      #- ENV=${ENV:-staging}
    profiles: ['manual']
