#
# app/docker-compose.online.yml
#
# Environment variables:
#   - ENV (default: 'staging'); the staging environment to work against.
#
# Intentions:
#   - Host the front end files with a cloud backend, according to 'ENV' env.var.
#
name: 245e80f4
services:
  vite-online:
    extends:
      file: dc.base.yml
      service: vite-base
    ports:
      - "$PORT:$PORT"

    volumes:
      #--- RO
      - ./tmp/firebase.${ENV:-staging}.config.json:/work/firebase.config.json:ro
      - ./tmp/.env.dev.${ENV:-staging}:/work/.env:ro
    command: sh -c '
      vite --mode dev_online
      && true
      '
      # Note: The '&& true' above (which is never reached), is needed for Ctrl-C to work, to terminate execution.
      #   If you know of a 'sh' flag that would do the same (wrap the command instead of executing it straight), let
      #   the author know.. #hack

    environment:
      - MODE=online
      #- ENV=${ENV:-staging}
    profiles: ['manual']
