#
# app/docker-compose.tools.prod.yml
#
services:
  #---
  # Separate target; build production delivery
  #
  # Note:
  #   Vite (3.0.0-alpha.1) has difficulties importing the Rollup plugin, if globally installed. Node.js, on the other
  #   hand, does not provide installation to '/node_modules'.
  #
  #   Solved by installing globally ('-g') and then linking to '/node_modules'.
  #
  #   See 'TRACK.md'; if 'rollup-plugin-visualizer' were to provide an 'exports' section, one day..
  #
  build:
    build:
      context: tools/vite.dc
    volumes:
      # --- RO
      - ./package.json:/work/package.json:ro
      - ./node_modules:/work/node_modules:ro         # note: should not have 'esbuild' in it
      - ./vite.config.js:/work/vite.config.js:ro     # Vite needs a restart to see config changes, thus 'ro'.
      - ./rollup.chunks.js:/work/rollup.chunks.js:ro
      - ../../firebase.${ENV:-staging}.js:/work/firebase.config.js:ro
      # --- RO (since we're a task)
      - ./src:/work/src:ro
      - ./prod:/work/prod:ro
      - ./public:/work/public:ro
      # --- Output
      - ./dist:/work/dist:delegated
      - ./stats.html:/work/stats.html:delegated
      # --- other
      - ../../../branding/favicon.png/:/work/public/favicon.png:ro
      - ./tmp/.vite:/work/tmp/.vite:delegated    # persistence between runs
    command: sh -c
      '
      npm install -g rollup-plugin-visualizer &&
      (cd / && mkdir node_modules && cd node_modules && ln -s $$NODE_PATH/rollup-plugin-visualizer .) &&

      ([ -z "${SENTRY_DSN:-}" ] || echo "VITE_SENTRY_DSN=${SENTRY_DSN:---}" >> .env) &&
      ([ -z "${RELEASE}" ] || echo "VITE_RELEASE=${RELEASE:---}" >> .env) &&
      ([ -z "$ENV" ] || echo "VITE_STAGE=${ENV:---}" >> .env) &&
      ([ -z "${SENTRY_SAMPLE_RATE:-}" ] || echo "VITE_SENTRY_SAMPLE_RATE=${SENTRY_SAMPLE_RATE:---}" >> .env) &&

      vite build
      '
      # Note: '{...:-}' (providing an empty default) avoids warnings; used for optional env.vars.

    #|environment:
    #|  - RELEASE
    #|  - ENV     # e.g. "staging"
    profiles: ['manual']

  # DISABLED (using native 'http-server')
  #|#---
  #|# Separate target (may be undocumented); serve the contents of 'dist/' (does NOT rebuild from sources!!!).
  #|#
  #|_serve:
  #|  build:
  #|    context: tools/serve.dc
  #|  ports:
  #|    - 8080:8080
  #|  volumes:
  #|    # --- RO
  #|    - ./dist:/work/dist:ro
  #|  command: sh -c
  #|    'http-server ./dist -p 8080
  #|    '
  #|  profiles: ['manual']
