#!/usr/bin/env node

/*
* Filter the output of 'firebase apps:sdkconfig' command to syntax suitable for 'firebase.staging.js' (in stdout).
*
* Context:
*   - run within Docker container
*/
import { readFileSync } from 'fs'

/*
* Sample input:
*   <<
*     // Copy and paste this into your JavaScript code to initialize the Firebase SDK.
*     // You will also need to load the Firebase SDK.
*     // See https://firebase.google.com/docs/web/setup for more details.
*
*     firebase.initializeApp({
*       "projectId": "groundlevel-160221",
*       "appId": "1:337689549369:web:27714618f3aec67899cbe8",
*       "storageBucket": "groundlevel-160221.appspot.com",
*       "locationId": "europe-west6",
*       "apiKey": "AIzaSyDl-5SnMLrnEXYN6JpXf0wMnXk8jVcs_mI",
*       "authDomain": "groundlevel-160221.firebaseapp.com",
*       "messagingSenderId": "337689549369",
*       "measurementId": "G-YCZ6YH84G4"
*     });
*   <<
*/
const input = readFileSync(0, 'utf-8');

const ReInput = /firebase\.initializeApp\(\s*({.+})\);\s*$/s;    // capture the JSON part
  //
  // Note: Regex 's' flag allows '.' to span over multiple lines. We know that the support is there, since we are running
  //      in Docker (Node.js 16).

const [_,c1] = ReInput.exec(input);

const json = JSON.parse(c1);

const { projectId, appId, locationId, apiKey, authDomain } = json;

if (! (projectId && appId && locationId && apiKey && authDomain)) {
  process.stderr.write(`ERROR: Some required value was not included in 'firebase apps:sdkconfig' output:\n\n${ input }`);
  process.exit(2);
}
  // tbd. not sure if 'locationId' is provided, if it's default

const out =
`// DO NOT EDIT THIS FILE. It's autogenerated.
// To have a permanent staging setup, see instructions in 'README'.
//
const config = {
  "projectId": "${projectId}",
  "appId": "${appId}",
  "locationId": "${locationId}",
  "apiKey": "${apiKey}",
  "authDomain": "${authDomain}",
};
export default config;
`;

process.stdout.write(out);
