#
# docker-compose.yml
#
# Launch emulators; provide a means to warm them up.
#
# Used by:
#   - manual development ('docker compose up -d' directly or via 'npm run up')
#   - CI
#     - with 'docker-compose.ci.yml' overrides
#
# Environment:
#   - CI_BUILDER_IMAGE (optional); name of the builder image.
#
# Intentions:
#   Within a Docker universe,
#     - launch Firebase Emulators using 'firebase.json'
#       - exposing ports for Firestore and Cloud Functions (Firebase Auth port not needed)
#
# Docker Compose (v3) note:
#   BE CAREFUL with use of pipe ('|') or '&&' in the commands! See -> https://stackoverflow.com/a/68590318/14455
#
# References:
#   Overview of Docker Compose (Docker docs)
#     -> https://docs.docker.com/compose/
#   Compose file version 3 reference
#     -> https://docs.docker.com/compose/compose-file/compose-file-v3/
#
services:
  # Launch Firebase Emulators, with certain warning and info messages suppressed.
  #
  emul:
    extends:
      file: docker-compose.base.yml
      service: emul-base
    ports:
      - "5002:5002"
      - "6767:6767"
      - "6800:6800"
      - "4000:4000"
        # Keep ports aligned with 'firebase.js'

    healthcheck:
      test: "nc -z localhost 6767 && nc -z localhost 5002 && nc -z localhost 6800 && sleep 1"
        # Note: 'nc' in that image doesn't handle checking multiple ports at once.
      interval: 0.7s
      start_period: 23s

  # WARM UP the engines
  #
  # Firebase Emulators are SLOW to wake. This part runs a minimal set of tests (the results of which are not used),
  # to wake up the necessary subsystems server-side. This results in more dependable test times in the actual tests.
  #
  warm-up:
    image: node:18-alpine
    volumes:
      # --- RO
      - ./node_modules:/work/node_modules:ro
      - ./jest.config.default.js:/work/jest.config.default.js:ro
      - ./tmp/firebase.json:/work/firebase.json:ro
      - ./package.json:/work/package.json:ro
      - ./test-fns:/work/test-fns:ro
      - ./test-firestore-rules:/work/test-firestore-rules:ro
      # HACK. during DEV, have 'file:~/Git/...' npm link resolve.
      #- ${HOME}/Git/firebase-jest-testing/package:/firebase-jest-testing/package:ro

    working_dir: /work
    command: sh -c
      'npm config set update-notifier false &&
      
      npm run dc:warm-up &&
      touch .healthy &&
        sleep infinity
      '
      # Note: Returning from Jest (npm command) is taking ~30s on Windows+WSL2. Reason unknown. Be patient! #83
      #       tbd. test - is this still so?
    environment:
      - EMUL_HOST=emul
      - WARM_UP_TIMEOUT=24000
          # Seen cold start execution times ('docker compose down; PROJECT_ID=demo-2 docker compose up warm-up'):
          #
          #   fns       rules
          #   ---       -----
          #   3889ms    1148ms        # MacOS Intel (DC 4.9.0)
          #
          #   ~~9.122s    ~~12.48s        # Cloud Build (CI)
          #
          #   Times are the _longest_ individual test's execution time, per run. These are where timeout is applied.

    depends_on:
      emul:
        condition: service_healthy

    healthcheck:
      test: "[ -f .healthy ] && echo 'HEALTHY!'"
      interval: 0.7s
      start_period: 80s

    # Enable manual launch to debug 'emul' launch, only.
    #profiles: ['manual']

  # A pass-through target.
  #
  # Used via 'docker compose run --rm warmed-up'.
  #
  # A separate target, so that the warm-up log output is always visible only in Docker Desktop, not the terminal
  # output for something like 'npm test' (if launched with a cold DC).
  #
  warmed-up:
    image: node:18-alpine
    command: sh -c true
    depends_on:
      warm-up:
        condition: service_healthy
    profiles: ['manual']
