#
# docker-compose.yml
#
# Launch emulators; provide a means to warm them up.
#
# Used by:
#   - manual development ('docker compose up -d' directly or via 'npm run up')
#   - CI
#     - with 'docker-compose.ci.yml' overrides
#
# Intentions:
#   Within a Docker universe,
#     - launch Firebase Emulators using 'firebase.json'
#       - exposing ports for Firestore and Cloud Functions (Firebase Auth port not needed)
#
# Docker Compose (v3) note:
#   BE CAREFUL with use of pipe ('|') or '&&' in the commands! See -> https://stackoverflow.com/a/68590318/14455
#
# References:
#   Overview of Docker Compose (Docker docs)
#     -> https://docs.docker.com/compose/
#   Compose file version 3 reference
#     -> https://docs.docker.com/compose/compose-file/compose-file-v3/
#
services:
  # Launch Firebase Emulators, with certain warning and info messages suppressed.
  #
  # Expects:
  #   - 'FUNCTIONS_PORT'
  #
  emul:
    extends:
      file: dc.base.yml
      service: emul-base
    ports:
      - "${FUNCTIONS_PORT}:${FUNCTIONS_PORT}"
      - "6767:6767"
      #- "6868:6868"    # no need to expose Realtime Database port, unless we want to test metrics/logging
      - "4000:4000"
        # Keep ports aligned with 'firebase.js'

    environment:
      - PROJECT_ID=demo-2
        # Project id for 'test-fns'.
        # Cloud Functions get triggered only for this project; Firebase Emulator UI shows only it.

    healthcheck:
      test: '
        nc -z localhost 6767 && 
        nc -z localhost ${FUNCTIONS_PORT} && 
        nc -z localhost 6868
        '
          # Note: 'nc' in that image doesn't handle checking multiple ports at once.
      interval: 0.7s
      start_period: 23s

  # WARM UP the engines
  #
  # Firebase Emulators are SLOW to wake. This part runs a minimal set of tests (the results of which are not used),
  # to wake up the necessary subsystems server-side. This results in more dependable test times in the actual tests.
  #
  # NOTE: Use Node.js 18 to have built-in fetch.
  #
  warm-up:
    image: node:18-alpine
    volumes:
      # --- RO
      - ./node_modules:/work/node_modules:ro
      - ./jest.config.default.js:/work/jest.config.default.js:ro
      - ./tmp/firebase.json:/work/firebase.json:ro
      - ./package.dc.json:/work/package.json:ro
      - ./test-firestore-rules:/work/test-firestore-rules:ro
      - ./test-fns:/work/test-fns:ro
      # HACK. during DEV, have 'file:~/Git/...' npm link resolve.
      #- ${HOME}/Git/firebase-jest-testing/package:/firebase-jest-testing/package:ro

    working_dir: /work
    command: sh -c
      'npm config set update-notifier false &&

      npm run dc:warm-up &&
      touch .healthy &&
      sleep infinity
      '
      # Note: Returning from Jest (npm command) is taking ~30s on Windows+WSL2. Reason unknown. Be patient! #83
      #       tbd. test - is this still so?
    environment:
      - EMUL_HOST=emul
      - WARM_UP_TIMEOUT=10000
        # tbd. document what that steers

    depends_on:
      emul:
        condition: service_healthy

    healthcheck:
      test: "[ -f .healthy ]"
      interval: 0.9s
      start_period: 240s
        #
        # That's long. But Windows 10 + WSL2 cold start times justify it.
        #
        #   - Lenovo X230 (ca. 2015), Windows 10, 12MB, DC 4.10.1: 3m11.946 s
        #   - macOS 12.4 Intel, DC 4.10.1 (3 cores, 2GB): 23.314, 25.263 s 
        #
        # Measure by:
        #   1. Delete all running DC containers
        #   2. $ time FUNCTIONS_PORT=5002 docker compose run --rm warmed-up

    # Enable manual launch to debug 'emul' launch, only.
    profiles: ['manual']

  # A pass-through target.
  #
  # Used via 'docker compose run --rm warmed-up'.
  #
  # A separate target, so that the warm-up log output is always visible only in Docker Desktop, not the terminal
  # output for something like 'npm test' (if launched with a cold DC).
  #
  warmed-up:
    image: node:18-alpine
    command: sh -c true
    depends_on:
      warm-up:
        condition: service_healthy
    profiles: ['manual']
