#
# docker-compose.app.yml
#
# A version of the DC definition for front-end development and testing.
#
# Expects:
#   'FUNCTIONS_PORT'  ! EXPERIMENTAL; still looking which is the best way to pass the port numbers..
#   'COMPOSE_IGNORE_ORPHANS=true'   to mitigate a warning, since we tie to a project ('app') that might have other running services
#
# Note:
#   Ports exposed at the host are defined so that they do not overlap with those of 'docker-compose.yml'.
#   This means backend containers can be left running while doing front-end development.
#
# References:
#   - Share Compose configurations between files and projects (Docker Compose docs)
#     -> https://docs.docker.com/compose/extends/
#
name: app   # allows us to be used from '../app', in the same network
services:
  emul-for-app:
    extends:
      file: dc.base.yml
      service: emul-base
    volumes:
      # --- RO
      - ./tmp/firebase.app.json:/work/firebase.json:ro

      # --- output
      - ./logs.app/firebase-debug.log:/work/firebase-debug.log:delegated
      - ./logs.app/firestore-debug.log:/work/firestore-debug.log:delegated
      - ./logs.app/database-debug.log:/work/database-debug.log:delegated
      - ./logs.app/ui-debug.log:/work/ui-debug.log:delegated

    # Ports need to be exposed to the host for a) Desktop Cypress use case, b) debugging (UI port).
    ports:
      - "${FUNCTIONS_PORT}:${FUNCTIONS_PORT}"
      - "${FIRESTORE_PORT}:${FIRESTORE_PORT}"
      - "${DATABASE_PORT}:${DATABASE_PORT}"     # realtime database, for metrics/logging
      - "${AUTH_PORT}:${AUTH_PORT}"
      - "${UI_PORT}:${UI_PORT}"
    environment:
      - PROJECT_ID=demo-main    # must match with what's in '../app/' (package[.dc].json, docker-compose.tools.local.yml)

    healthcheck:
      test: '
        nc -z localhost ${FIRESTORE_PORT} && 
        nc -z localhost ${FUNCTIONS_PORT} && 
        nc -z localhost ${DATABASE_PORT} &&
        nc -z localhost ${AUTH_PORT}
        '
          # Note: 'nc' in that image doesn't handle checking multiple ports at once.
      interval: 1.0s
      start_period: 25s

  # No warm-up (as with the backend)

  emul-for-app-launched:
    image: node:16-alpine
    command: sh -c true
    depends_on:
      emul-for-app:
        condition: service_healthy
    profiles: ['manual']
