#
# backend/docker-compose.app.ci.yml
#
# Extends 'docker-compose.ci.yml' so that:
#   - authentication is included
#   - Realtime Database (for metrics & logs) is included
#
# Note: Unlike with dev, we use the same ports as the backend testing does. In development, one might want to run them
#     at the same time, whereas in CI, it's always either or. So, we can keep things simpler.
#     Also, we don't need to do '.app' stuff. It's all the same.
#
# Expects:
#   - (same as 'docker-compose.ci.yml')
#
services:
  emul-for-app:
    extends:
      file: docker-compose.ci.yml
      service: emul
    volumes:
      #--- RO
      - ./tmp/firebase.app.ci.json:/work/firebase.json:ro
      - ./database.rules.app.json:/work/database.rules.app.json:ro
      #--- Output
      - ./database-debug.log:/work/database-debug.log:delegated

    # Ports not needed; tests will run directly against 'emul-for-app' hostname.
    environment:
      - PROJECT_ID=demo-main

    #|healthcheck:
    #|  test: '
    #|    nc -z localhost 6767 &&
    #|    nc -z localhost 5002
    #|  '
    #|    #nc -z localhost 9100 &&
    #|    #nc -z localhost 6868
    #|  interval: 0.5s
    #|  start_period: 30s
    #|  # Cannot merge with base (backend, sans auth and database) easily; duplicating all services here.

    # Allows the ports to be seen (as 'emul-for-app:{port}') by Cloud Build steps.
    #
    network_mode: cloudbuild
    container_name: emul-for-app

  emul-for-app-warmed-up:
    image: node:18-alpine
    volumes:
      # --- RO
      - ./dc/waky-waky:/work/waky-waky:ro
      - ./tmp/firebase.app.ci.json:/work/firebase.app.json:ro

    working_dir: /work
    command: sh -c '
      echo "{ \"type\":\"module\" }" > package.json &&
      
      node waky-waky/index.js metrics-and-logging-proxy-v0
      '
    environment:
      - EMUL_HOST=emul-for-app
      - PROJECT_ID=demo-main
    depends_on:
      emul-for-app:
        condition: service_healthy

    network_mode: cloudbuild                  # so 'emul-for-app' is seen
    container_name: emul-for-app-warmed-up    # just for logs
    profiles: ['manual']
