#
# ci/cloudbuild.merged.backend.yaml
#
# Triggers:
#   - new stuff is merged to a branch ('$BRANCH_NAME'); changes either in 'packages/backend/**',
#     root 'package.json' or 'tools'
#
# GCP Project:
#   Same GCP project that carries the Firebase deployment.
#
# Responsibility:
#   - test and deploy backend
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# References:
#   - Cloud Build > Substituting variable values
#     https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values

steps:
# Flight check: not to be run from the 'ci-builder'
- name: $_1
  entrypoint: bash
  args: ['-c', '[[ $PROJECT_ID != ci-builder ]]']

# Root install
- name: $_1
  entrypoint: bash
  args: ['-c', 'apk --no-cache add patch && npm install']

# Tests (keep similar to 'cloudbuild.master-pr.backend.yaml')
- name: $_1
  entrypoint: npm
  args: ['install']
  dir: packages/backend
- name: $_1
  entrypoint: firebase
  args: ['use', '$PROJECT_ID']
  dir: packages/backend
- name: $_1
  entrypoint: npm
  args: ['run', 'ci:test']
  dir: packages/backend
# DEPLOY
- name: $_1
  entrypoint: npm
  args: ['run', 'ci:deploy']
  dir: packages/backend

# --- Timeout
#
# Cloud Build:  4:58
#
timeout: 400s

# Note: Substitutions don't seem to get parsed recursively (would like to use '$_BUILDER_TAG' to define the image)
#
substitutions:
  #_BUILDER_TAG: 9.16.0-node16-npm7
  _1: gcr.io/ci-builder/firebase-ci-builder:9.16.0-node16-npm7
