#
# ci/cloudbuild.app.yaml
#
# Trigger:
#   - PR is made or changed; changes affect 'packages/app' or 'packages/app-deploy-ops' (or '/package.json', or 'tools/**')
#
# Cloud Build project:
#   - Common CI builder (not project specific; no deploys!)
#
# Uses images:
#   - node:16-alpine
#   - firebase-ci-builder   (pushed to Container Registry; used via Docker Compose)
#   - docker/compose
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Note:
#   Using 'node:16' to run 'npm install' means that the packages are installed as root, and 'node_modules' is read-only
#   to regular users (of other images). This is normally not a concern.

steps:
# Install
#
- name: node:16-alpine
  entrypoint: sh
  args: ['-c', '
    npm config set update-notifier false &&
    
    npm install &&
    npm --prefix packages/backend install --no-optional &&
    npm --prefix packages/app install --no-optional
  ']
    # Note: Not sure if '--no-optional' makes any difference

  env: ['CYPRESS_INSTALL_BINARY=0']

# --- App
#
# Launch emulators and Vite; keeps them running in the background.
#
# Note: Launching emulators just like 'start:app' (but cannot mix npm and DC).
# Note: No priming of data & users is needed. Cypress tests carry their own (we do 'npm test', not dev).
#
- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.app.yml', '-f', 'docker-compose.app.ci.yml', 'run', '--rm', 'emul-for-app-launched']
  dir: packages/backend
  env:
    - CI_BUILDER_IMAGE=gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}

- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.yml', '-f', 'docker-compose.ci.yml', 'run', 'vite-local-launched']
  dir: packages/app
  env:
    - CI_BUILDER_IMAGE=gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}

- name: cypress/included:${_CYPRESS_TAG}
  args: ['run', '--headless']
  dir: packages/app
  env:
    - CYPRESS_baseUrl=http://vite:3000
    - CYPRESS_defaultCommandTimeout=10000
    #
    # Tests durations:
    #   1: 7541, 7682, 8565 ms
    #   2: 3980, 4289, 3804 ms

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'lint']
  dir: packages/app

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'build']
  dir: packages/app

# --- Timeout
#
# Cloud Build:
#   - with tests, and build: 4:54
#
#   - with tests (no build): 5:54 (old)
#
timeout: 500s

substitutions:
  _BUILDER_TAG: 10.6.0-node16-npm8
  _DOCKER_COMPOSE_TAG: 1.29.2
    # https://hub.docker.com/r/docker/compose/tags?page=1&ordering=last_updated
  _CYPRESS_TAG: 9.5.4
    # https://hub.docker.com/r/cypress/included/tags?page=1&ordering=last_updated
