#
# ci/cloudbuild.pr.app.yaml
#
# Trigger:
#   - PR is made or changed; changes affect 'packages/app' or 'packages/app-deploy-ops'
#
# Cloud Build project:
#   - Common CI builder (not project specific; no deploys!)
#
# Uses images:
#   - node:16
#   - firebase-ci-builder:${_BUILDER_TAG}   (pushed to Container Registry)
#   - docker
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#

steps:
# Root install
#
- name: node:16
  entrypoint: npm
  args: ['install']

# --- Backend
#
# Do not care to test it - separate PR task does it.
#
- name: node:16
  entrypoint: npm
  args: ['install']
  dir: packages/backend

# --- App
#
#- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
- name: node:16
  entrypoint: npm
  args: ['install']
  dir: packages/app
  env: ['CYPRESS_INSTALL_BINARY=0']

# Q: Is this able to pull the 'firebase-ci-builder' image from the Container Registry, as referenced in the 'docker-compose.yml'?
#
- name: gcr.io/cloud-builders/docker
  entrypoint: docker
  args: ['compose', 'run', 'cypress']
    # same as 'npm run ci:test' would do
  dir: packages/app

#- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
- name: node:16
  entrypoint: npm
  args: ['run', 'lint']
  dir: packages/app
#- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
- name: node:16
  entrypoint: npm
  args: ['run', 'build']
  dir: packages/app

# --- Timeout
#
# Local:        ...
# Cloud Build:  2:03 (without Cypress tests)
#
timeout: 240s

substitutions:
  #_BUILDER_TAG: 9.16.0-node16-npm7
  #_BUILDER_TAG: 9.12.1-node16-npm7
