#
# ci/cloudbuild.app.merged.yaml
#
# Triggers:
#   - new stuff is merged to a branch ('$BRANCH_NAME'); changes either in 'packages/app/**' or root 'package.json'.
#
# Cloud Build project:
#   Same GCP project that carries the Firebase deployment.
#
# Responsibility:
#   - (maybe test,) build and deploy front-end
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Staging:
#   While development uses 'firebase.${ENV:-staging}.js' in the project root, here the stage comes from the _GCP
#   project itself_.
#
# References:
#   - Cloud Build > Substituting variable values
#     https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
#
steps:
# Flight check: don't run deploy off general 'ci-builder'
- name: node:16-alpine
  entrypoint: sh
  args: ['-c',
    '[ $PROJECT_ID != ci-builder ] || ( >&2 echo "ERROR: Please change to the deployment project: gcloud config set project <project-id>"; false ) &&

    [ ! -z $$SENTRY_DSN ] || ( >&2 echo "ERROR: Please provide ''SENTRY_DSN'' env.var. to enable operational monitoring."; false ) &&
    
    [ ! -z $_STAGE ] || ( >&2 echo "ERROR: Please provide ''_STAGE'' substitution, e.g. with ''--substitutions _STAGE=abc'' or a CI task setting."; false )
    '
  ]
  secretEnv:
    - SENTRY_DSN

# Install
- name: node:16-alpine
  entrypoint: sh
  args: ['-c', '
    npm config set update-notifier false &&

    npm install &&
    npm --prefix packages/app install --no-optional
  ']
  env: ['CYPRESS_INSTALL_BINARY=0']
     # npm --prefix packages/backend install --no-optional &&     <-- put back if re-enabling emulators

# Test
#
# 1-to-1 from 'cloudbuild.app.yaml'.
#
#| TEMPORARILY DISABLED (did not pass; tbd.)
#|- name: docker/compose:${_DOCKER_COMPOSE_TAG}
#|  args: ['-f', 'docker-compose.app.yml', '-f', 'docker-compose.app.ci.yml', 'run', '--rm', 'emul-for-app-launched']
#|  dir: packages/backend
#|  env:
#|    - CI_BUILDER_IMAGE=$_1
#|
#|- name: docker/compose:${_DOCKER_COMPOSE_TAG}
#|  args: ['-f', 'docker-compose.yml', '-f', 'docker-compose.ci.yml', 'run', 'vite-local-launched']
#|  dir: packages/app
#|  env:
#|    - CI_BUILDER_IMAGE=$_1
#|
#|- name: cypress/included:${_CYPRESS_TAG}
#|  args: ['run', '--headless']
#|  dir: packages/app
#|  env:
#|    - CYPRESS_baseUrl=http://vite:3000
#|    - CYPRESS_defaultCommandTimeout=10000

# Build
#

# Sign in (to Firebase) and create a 'firebase.live.js' that captures the current project's config.
#
- name: $_1
  entrypoint: bash
  args: ['-c', '
    firebase use $PROJECT_ID && 
    CAPTURE=$$( firebase apps:sdkconfig
      | grep -E ''^\s+".+":\s.+,'' | grep -E "projectId|appId|locationId|apiKey|authDomain"
    ) &&

    echo "export default { $$CAPTURE }" > ../../firebase.$_STAGE.js
  ']
  dir: packages/backend

- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.tools.prod.yml', 'run', 'build']
  dir: packages/app
  env:
    - ENV=$_STAGE
    - RELEASE=${SHORT_SHA:-0}
    #- SENTRY_SAMPLE_RATE=${_SENTRY_SAMPLE_RATE:-}
  secretEnv:
    - SENTRY_DSN

# DEPLOY
#
- name: $_1
  entrypoint: bash
  args: ['-c', '
    firebase use $PROJECT_ID &&
    firebase deploy --only hosting
  ']
  dir: packages/app

# --- Timeout
#
# Cloud Build (no tests): 2:00, 1:52
#
# (old CI; no tests): 2:03
#
timeout: 400s

# Note: Substitutions don't seem to get parsed recursively (would like to use '$_BUILDER_TAG' to define the image)
#
substitutions:
  #_BUILDER_TAG: 10.6.0-node16-npm8
  _1: gcr.io/ci-builder/firebase-ci-builder:11.2.0-node18-npm8
  _DOCKER_COMPOSE_TAG: 1.29.2
  #_CYPRESS_TAG: 9.6.0
  _STAGE: manual      # set by CI, eg. "staging"
  #_SENTRY_SAMPLE_RATE: "1.0" # overridable by CI

# API Keys heading for the front end are not really hard secrets, but let's treat them as such, anyways.
#
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SENTRY_DSN/versions/latest
      env: 'SENTRY_DSN'
