#
# ci/cloudbuild.pr.app.yaml
#
# Trigger:
#   - PR is made or changed; changes affect 'packages/app' or 'packages/app-deploy-ops'
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#

substitutions:
  _BUILDER_TAG: 9.12.1-node16-npm7
  #_CYPRESS_IMAGE: cypress/included:7.4.0

steps:
# Root install
#
# Note: 'patch' (not part of the builder image) must be added and used within the same CI step, since changes outside
#       of '/workspace' don't carry from step to step.
#
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: bash
  args: ['-c', 'apk --no-cache add patch && npm install']

# --- Backend
#
# Do not care to test it - separate PR task does it.
#
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['install']
  dir: packages/backend

# --- App
#
# tbd. Cypress is not available on images based on Alpine.
#     - track https://github.com/cypress-io/cypress/issues/419
#
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['install']
  dir: packages/app
  env:
  - 'CYPRESS_CACHE_FOLDER=/workspace/.tmp/Cypress'
#- name: gcr.io/$PROJECT_ID/firebase-ci-builder-cypress:${_CYPRESS_TAG}
#  entrypoint: npm
#  args: ['run ci:test']
#  dir: packages/app
#  env:
#  - 'CYPRESS_CACHE_FOLDER=/workspace/.tmp/Cypress'
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['run', 'lint']
  dir: packages/app
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['run', 'build']
  dir: packages/app-deploy-ops

# --- Timeout
#
# Local:        ...
# Cloud Build:  1:52 (without Cypress tests)
#
#timeout: 240s
