#
# ci/cloudbuild.app.merged.yaml
#
# Triggers:
#   - new stuff is merged to a branch ('$BRANCH_NAME'); changes either in 'packages/app/**' or root 'package.json'.
#
# Cloud Build project:
#   Production/staging GCP project (deploys to itself).
#
# Responsibility:
#   - build and deploy front-end
#
# Uses images:
#   - node:{16|18}-alpine (stock image)
#   - firebase-emulators  (pushed to Artifact Registry)   contains Firebase CLI we use for deployment
#   - gsutil              (Cloud Build built-in image)
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# References:
#   - Cloud Build > Substituting variable values
#     https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
#
steps:
#TEMP; TERMINUS
- name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args: ['-c', '
    echo "COMMIT_SHA: ${COMMIT_SHA}" &&
    echo "REVISION_ID: ${REVISION_ID}" &&
    echo "SHORT_SHA: ${SHORT_SHA}" &&
    echo "REPO_NAME: ${REPO_NAME}"
  ']
#
# We need the commit SHA one past the HEAD.
#
# The 'git' checkout is shallow:
#   <<
#     Step #1: HEAD:
#     Step #1: 970015b
#     Step #1: HEAD~1:
#     Step #1: fatal: Needed a single revision
#   <<
- name: gcr.io/cloud-builders/git
  entrypoint: sh
  args: ['-c', '
    cat .git/config &&
    git fetch --depth=2 &&
    echo "HEAD:" &&
      git rev-parse --short HEAD &&
    echo "HEAD~1:" &&
      git rev-parse --short HEAD~1 &&
    false
  ']
    #echo "*** Running for: ${SHORT_SHA} ***" &&

# Flight check
- name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args: ['-c', '
    [ $PROJECT_ID != ${_MY_BUILDER} ] || ( >&2 echo "ERROR: Please change to the deployment project: gcloud config set project <project-id>"; false ) &&
    [ ! -z $$SENTRY_DSN ] || >&2 echo "WARN: ''SENTRY_DSN'' missing; no operational monitoring!" &&
    
    if [ -z ${SHORT_SHA} ]; then
      >&2 echo "ERROR: No ''SHORT_SHA'' detected. If this is a manual run, provide one by ''--substitutions=SHORT_SHA=xxx''."; false
    ; else
      gsutil cat ${_GS_TOUCH_PATH}/${SHORT_SHA} ||
        ( >&2 echo "ERROR: No evidence that tests would have passed. ''${_GS_TOUCH_PATH}/${SHORT_SHA}'' does not exist"; false )
    ; fi
  ']
  secretEnv:
    - SENTRY_DSN

# Install
- name: node:${_NODE_VER}-alpine
  entrypoint: sh
  args: ['-c', '
    npm config set update-notifier false &&

    npm install &&
    npm --prefix packages/app install --omit=optional
  ']
    # Note: '--omit=optional' does not matter, in practise (the idea was to not pull in Vite).
  env:
    - CYPRESS_INSTALL_BINARY=0

  # State:
  #   - packages/app/firebase.json    has the deployment configuration (based on 'firebase.hosting.js')

# Sign in to Firebase; capture the "access values"
#
- name: $_1
  entrypoint: sh
  args: ['-c', '
    firebase use $PROJECT_ID && 

    firebase apps:sdkconfig | grep -E ''^\s+".+":\s.+,'' | grep -E "projectId|appId|locationId|apiKey|authDomain|databaseURL"
      > .capture &&

    echo "export default { $$( cat .capture ) }" > firebase.config.js
  ']
  dir: packages/app

  # State:
  #   - packages/app/firebase.config.js    has the Firebase server "access values", to be baked into the client

# Build
- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.tools.ci.yml', 'run', 'build']
  dir: packages/app
  env:
    - RELEASE=${SHORT_SHA:-0}
    #- SENTRY_SAMPLE_RATE=${_SENTRY_SAMPLE_RATE:-}
    - FIREBASE_SERVER_CONFIG_JS=./firebase.config.js
  secretEnv:
    - SENTRY_DSN

# DEPLOY
#
- name: $_1
  entrypoint: sh
  args: ['-c', '
    firebase deploy --only hosting
  ']
  dir: packages/app

# --- Timeout
#
# Cloud Build:  1:30
#
timeout: 400s

# Note: Substitutions don't seem to get parsed recursively (would like to use '$_BUILDER_TAG' to define the image)
#
substitutions:
  _1: us-central1-docker.pkg.dev/ci-builder/builders/firebase-emulators:11.3.0
  _DOCKER_COMPOSE_TAG: 1.29.2
  _NODE_VER: "18"
  _GS_TOUCH_PATH: gs://ci-builder_cloudbuild/.passed.app    # where successful tests are marked
  _MY_BUILDER: ci-builder

# Anything baked into the front end are not really hard secrets, but let's treat them as such.
#
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SENTRY_DSN/versions/latest
      env: 'SENTRY_DSN'
