#
# ci/cloudbuild.backend.yaml
#
# Triggers:
#   - PR is made or changed; changes affect 'packages/backend' (or '/package.json')
#
# Cloud Build project:
#   - Common CI builder (not project specific; no deploys!)
#
# Uses images:
#   - node:18-alpine      (stock image)
#   - firebase-emulators  (pushed to Artifact Registry)
#   - docker/compose      (stock image)
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables:
#     PWD=/workspace
#     HOME=/builder/home
#     BUILDER_OUTPUT=/builder/outputs
#
# Note:
#   Using 'node:16' to run 'npm install' means that the packages are installed as root, and 'node_modules' is read-only
#   to regular users (of other images). This is normally not a concern.
#
#   tbd. Moved to 'node:18'. Does the above still hold? #contribute
#

steps:
# Install
#
- name: node:${_NODE_VER}-alpine
  entrypoint: sh
  args: ['-c', '
    [ $PROJECT_ID == ci-builder ] || ( >&2 echo "ERROR: Please change to the ''ci-builder'' project: gcloud config set project ci-builder"; false ) &&

    npm config set update-notifier false &&

    npm install &&
    npm --prefix packages/backend install
  ']
  # State:
  #   - 'packages/backend/functions/node_modules' have been populated
  #   - 'packages/backend/tmp/firebase.json' has been created
  #   - 'packages/backend/tmp/database.rules.json' has been created

# DEBUG:
#
# USE THIS TO DEBUG CASES where the emulators don't start (or to see warm-up timings).
#
# Note: 'docker compose up' never returns, so if this is enabled, it's eventually a timeout.
#
#|- name: docker/compose:${_DOCKER_COMPOSE_TAG}
#|  #args: ['-f', 'docker-compose.ci.yml', 'up', 'emul']
#|  args: ['-f', 'docker-compose.ci.yml', 'up', 'emul-is-up']
#|  dir: packages/backend
#|  env:
#|    - CI_BUILDER_IMAGE=us-central1-docker.pkg.dev/${PROJECT_ID}/${_AR_FOLDER}/firebase-emulators:${_BUILDER_TAG}
#|    - FIRESTORE_PORT=6767
#|    - FUNCTIONS_PORT=5002
#|    - DATABASE_PORT=6800

# --- --- --- 📣⚠️🪤🚨
# WARNING!!!
#
#   If there is a problem with Cloud Functions, INSTEAD OF EXITING, THE EMULATORS KEEP RUNNING!! This is NOT
#   ideal for developers, because it gives the feeling things would be right. INSTEAD, FIREBASE EMULATORS SHOULD FAIL
#   if there is a major problem like Cloud Functions cannot be started. **PLEASE PUT PRESSURE ON FIREBASE TO CHANGE
#   THIS BEHAVIOUR if you agree with it.** Saves all of our time. Thank You.
#
#   ^-- Above applies only to the case where there would be failures INITIALLY, when the emulators are loaded.
#       In this case, I think emulators should refuse to launch. The emulators also have hot-reload capabilities
#       for functions and Rules, and for this use case, it's vital that they keep running.
#
# --- --- --- 📣⚠️🪤🚨

# Launch emul in DC, keeps them running in the background.
#
- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.ci.yml', 'run', 'emul-is-healthy']
  dir: packages/backend
  env:
    - CI_BUILDER_IMAGE=us-central1-docker.pkg.dev/${PROJECT_ID}/${_AR_FOLDER}/firebase-emulators:${_BUILDER_TAG}
    - FIRESTORE_PORT=6767
    - FUNCTIONS_PORT=5002
    - DATABASE_PORT=6800

# Warm-up
#
# In development, we do warm-up but that's not really needed, in CI. Results are below. Enable the warm-up block if
# you wish to confirm them.
#
#
# |           | userInfo (fns) | rules |
# | --------- | -------------- | ----- |
# | first run | 2894, 3306 ms | 762, 907 ms |    <-- good enough to use (Jul 22)
# | (2nd run) |  422 ms | 631 ms |

#|- name: node:18-alpine
#|  entrypoint: npm
#|  args: ['run', 'ci:test']
#|  dir: packages/backend
#|  env:
#|    - EMUL_HOST=emul

- name: node:18-alpine
  entrypoint: npm
  args: ['run', 'ci:test']
  dir: packages/backend
  env:
    - EMUL_HOST=emul
    - WARM_UP_TIMEOUT=4000    # extend the timeout; development may use 2s

- name: node:${_NODE_VER}-alpine
  entrypoint: npm
  args: ['run', 'lint']
  dir: packages/backend

# --- Timeout
#
# Cloud Build:
#   - 2:06
#
# OLD:
#   - 2:06  (no functions test)
#
timeout: 300s

substitutions:
  _BUILDER_TAG: 11.2.1
  _DOCKER_COMPOSE_TAG: 1.29.2
  _NODE_VER: "16"
  _AR_FOLDER: builders
    # You may use any name, or create such a folder in AR.
