#
# ci/cloudbuild.master-pr.app.yaml
#
# Trigger:
#   - PR is made or changed; changes affect 'packages/app' or 'packages/app-deploy-ops'
#
# Cloud Build project:
#   - Common CI builder (not project specific; no deploys!)
#
# Uses images:
#   - node:16
#   - firebase-ci-builder   (pushed to Container Registry; used via Docker Compose)
#   - docker
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#

steps:
# Root install
#
- name: node:16
  entrypoint: npm
  args: ['install']

# --- Backend
#
# Do not care to test it - separate PR task does it.
#
- name: node:16
  entrypoint: npm
  args: ['install']
  dir: packages/backend

# --- App
#
- name: node:16
  entrypoint: npm
  args: ['install']
  dir: packages/app
  env: ['CYPRESS_INSTALL_BINARY=0']

# On 6-Aug-2021, 'gcr.io/cloud-builders/docker':
#   https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker
#
#   - is version 19.03.8
#   - does not have 'docker compose' or 'docker-compose'
#
#   <<
#     # docker compose up
#     docker: 'compose' is not a docker command.
#   <<
#
# See #76 for more information: https://github.com/akauppi/GroundLevel-firebase-es/issues/76
#
#- name: gcr.io/cloud-builders/docker
#  entrypoint: docker
#  args: ['compose', 'run', 'cypress']
#    # same as 'npm run ci:test' would do
#  dir: packages/app

# Or:
#- name: docker/compose
#  entrypoint: docker-compose
#  args: ['run', 'cypress']
#    # same as what 'npm run ci:test' would do
#  dir: packages/app

- name: node:16
  entrypoint: npm
  args: ['run', 'lint']
  dir: packages/app
- name: $_1
  entrypoint: npm
  args: ['run', 'build']
  dir: packages/app

# --- App-deploy-ops
#
# Try that the code builds with fake access values.
#
- name: node:16
  entrypoint: npm
  args: ['install']
  dir: packages/app-deploy-ops
- name: node:16
  entrypoint: sh
  args: ['-c', 'echo "export default { }" > ../../firebase.fake.js']
  dir: packages/app-deploy-ops
- name: $_1
  entrypoint: npm
  args: ['run', 'build']
  dir: packages/app-deploy-ops
  env: ['ENV=fake', 'RAYGUN_API_KEY=x']

# --- Timeout
#
# Cloud Build:  2:33 (without Cypress tests)
#
timeout: 240s

substitutions:
  # Has Node 16 and bash
  _1: gcr.io/ci-builder/firebase-ci-builder:9.16.0-node16-npm7
