#
# ci/cloudbuild.app.yaml
#
# Trigger:
#   - PR is made or changed; changes affect 'packages/app' (or '/package.json')
#
# Cloud Build project:
#   - Common CI builder (not project specific; no deploys!)
#
# Uses images:
#   - node:16-alpine
#   - firebase-ci-builder   (pushed to Container Registry; used via Docker Compose)
#   - docker/compose
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Note:
#   Using 'node:16' to run 'npm install' means that the packages are installed as root, and 'node_modules' is read-only
#   to regular users (of other images). This is normally not a concern.

steps:

# Versions (23-May-22):
#   - default is "19.03.9, build 9d988398e7"
#   - available: "20.10.14, build a224086"    <-- note: tag 20.10.13 reports this
#
#|- name: gcr.io/cloud-builders/docker:20.10.13
#|  args: ['--version']
#|- name: gcr.io/cloud-builders/docker:20.10.13
#|  entrypoint: "docker-compose"
#|  args: ['--help']

# Install
#
- name: node:16-alpine
  entrypoint: sh
  args: ['-c', '
    [ $PROJECT_ID == ci-builder ] || ( >2& echo "ERROR: Please change to the ''ci-builder'' project: gcloud config set project ci-builder"; false ) &&

    npm config set update-notifier false &&
    
    echo ''export default {}'' > firebase.fake.js &&
    
    npm install &&
    npm --prefix packages/backend install &&
    npm --prefix packages/app install --no-optional
  ']
    # Note: '--no-optional' can make a slight speedup, not installing 'vite', 'rollup' etc. (that then get immediately
    #   removed). However, have not measured.

  env: ['CYPRESS_INSTALL_BINARY=0']

# --- App
#
# Launch emulators and Vite; keeps them running in the background.
#
# Note: No priming of data & users is needed. Cypress tests carry their own (we do 'npm test', not dev).
#
- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.app.yml', '-f', 'docker-compose.app.ci.yml', 'run', 'emul-for-app-launched']
  dir: packages/backend
  env:
    - CI_BUILDER_IMAGE=gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}

- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.local.yml', '-f', 'docker-compose.ci.yml', 'run', 'vite-for-ci-launched']
  dir: packages/app
  env:
    - PORT=3002

# BROKEN.
#
# Sometimes just gets stuck.
#
# First test might pass, but second (Joe sign-in) fails:
#   <<
#     FirebaseError: Firebase: A network AuthError (such as timeout, interrupted connection or unreachable host) has occurred. (auth/network-request-failed).
#   <<
#
- name: cypress/included:${_CYPRESS_TAG}
  args: ['run', '--headless']
  dir: packages/app
  env:
    - CYPRESS_baseUrl=http://vite:3002
    - CYPRESS_defaultCommandTimeout=20000
    #
    # Tests durations:
    #   1: 8555 ms
    #   2: -
    #
    # Test durations (old; different Cypress etc.):
    #   1: 7541, 7682, 8565 ms
    #   2: 3980, 4289, 3804 ms

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'lint']
  dir: packages/app

# Just check that it builds. Can have a fake Firebase config.
#
- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.tools.prod.yml', 'run', 'build']
  dir: packages/app
  env:
    - ENV=fake

# --- Timeout
#
# Cloud Build:
#   - with tests, and build: 4:54
#
#   - with tests (no build): 5:54 (old)
#
timeout: 500s

substitutions:
  _BUILDER_TAG: 11.0.1-node18-npm8
  _DOCKER_COMPOSE_TAG: 1.29.2
    # https://hub.docker.com/r/docker/compose/tags?page=1&ordering=last_updated
  _CYPRESS_TAG: 9.6.0
    # https://hub.docker.com/r/cypress/included/tags?page=1&ordering=last_updated
