#
# ci/cloudbuild.backend.yaml
#
# Triggers:
#   - PR is made or changed; changes affect 'packages/backend' (or '/package.json', or 'tools/**')
#
# Cloud Build project:
#   - Common CI builder (not project specific; no deploys!)
#
# Uses images:
#   - node:16-alpine
#   - firebase-ci-builder   (pushed to Container Registry)
#   - docker/compose
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Note:
#   Using 'node:16' to run 'npm install' means that the packages are installed as root, and 'node_modules' is read-only
#   to regular users (of other images). This is normally not a concern.
#

steps:
# Root install
#
- name: node:16-alpine
  entrypoint: npm
  args: ['install']

# Backend
#
- name: node:16-alpine
  entrypoint: npm
  args: ['install']
  dir: packages/backend

# DEBUG:
#
# USE THIS TO DEBUG CASES where the emulators don't start (or to see warm-up timings).
#
#>- name: docker/compose:${_DOCKER_COMPOSE_TAG}
#>  args: ['-f', 'docker-compose.yml', '-f', 'docker-compose.ci.yml', 'run', 'warm-up']
#>  dir: packages/backend
#>  env:
#>    - CI_BUILDER_IMAGE=gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}
#>    - NODE_V=16

# --- --- --- 📣⚠️🪤🚨
# WARNING!!!
#
#   If there is a problem with Cloud Functions, INSTEAD OF EXITING, THE EMULATORS KEEP RUNNING!! This is NOT
#   ideal for developers, because it gives the feeling things would be right. INSTEAD, FIREBASE EMULATORS SHOULD FAIL
#   if there is a major problem like Cloud Functions cannot be started. **PLEASE PUT PRESSURE ON FIREBASE TO CHANGE
#   THIS BEHAVIOUR if you agree with it.** Saves all of our time. Thank You.
#
#   ^-- Above applies only to the case where there would be failures INITIALLY, when the emulators are loaded.
#       In this case, I think emulators should refuse to launch. The emulators also have hot-reload capabilities
#       for functions and Rules, and for this use case, it's vital that they keep running.
#
# --- --- --- 📣⚠️🪤🚨

# Launch emul/warm-up in DC, keeps them running in the background.
#
- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.yml', '-f', 'docker-compose.ci.yml', 'run', 'warmed-up']
  dir: packages/backend
  env:
    - CI_BUILDER_IMAGE=gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'ci:test']
  dir: packages/backend
  env:
    - EMUL_HOST=emul

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'lint']
  dir: packages/backend

# --- Timeout
#
# Cloud Build (Alpine Node image):
#   - DC/Docker, with lint:     2:09, 2:24
#
timeout: 300s

# (Old results for reference, before 10-Sep-21; 'node:16' image)
# Cloud Build
#   - native, no lint:          1:51, 1:45  # (old results)
#   - DC/Docker, with lint:     3:13
#   - DC/native, with lint:     2:35

substitutions:
  #_BUILDER_TAG: 9.17.0-node16-npm7
  _BUILDER_TAG: 10.4.0-node16-npm8
  _DOCKER_COMPOSE_TAG: 1.29.2
