#
# ci/cloudbuild.master-pr.app.yaml
#
# Trigger:
#   - PR is made or changed; changes affect 'packages/app' or 'packages/app-deploy-ops'
#
# Cloud Build project:
#   - Common CI builder (not project specific; no deploys!)
#
# Uses images:
#   - node:16
#   - firebase-ci-builder   (pushed to Container Registry; used via Docker Compose)
#   - docker/compose
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Note:
#   Using 'node:16' to run 'npm install' means that the packages are installed as root, and 'node_modules' is read-only
#   to regular users (of other images). This is normally not a concern.

steps:
# Root install
#
- name: node:16
  entrypoint: npm
  args: ['install']

# --- Backend
#
# Do not care to test it - separate PR task does it.
#
- name: node:16
  entrypoint: npm
  args: ['install']
  dir: packages/backend

# --- App
#
- name: node:16
  entrypoint: npm
  args: ['install']
  dir: packages/app
  env: ['CYPRESS_INSTALL_BINARY=0']

- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['run', 'cypress',
     '--build-arg', 'CYPRESS_TAG=8.3.99'
  ]
  dir: packages/app
  env: [
    'CI_BUILDER_IMAGE=gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}'
  ]

- name: node:16
  entrypoint: npm
  args: ['run', 'lint']
  dir: packages/app
- name: node:16
  entrypoint: npm
  args: ['run', 'build']
  dir: packages/app
    # tbd. use 'n16-user' if needs bash

# --- App-deploy-ops
#
# Try that the code builds with fake access values.
#
- name: node:16
  entrypoint: npm
  args: ['install']
  dir: packages/app-deploy-ops
- name: node:16
  entrypoint: sh
  args: ['-c', 'echo "export default { }" > ../../firebase.fake.js']
  dir: packages/app-deploy-ops
#- name: node:16
#  # likely with n16-user???
#  entrypoint: npm
#  args: ['run', 'build']
#  dir: packages/app-deploy-ops
#  env: ['ENV=fake', 'RAYGUN_API_KEY=x']

# --- Timeout
#
# Cloud Build:  2:33, 2:13, 2:04 (without Cypress tests)
#
timeout: 500s

substitutions:
  # Has Node 16 and bash
  #_1: gcr.io/${PROJECT_ID}/firebase-ci-builder:9.16.0-node16-npm7
  #
  _BUILDER_TAG: 9.16.0-node16-npm7
  #
  _DOCKER_COMPOSE_TAG: 1.29.2
    # https://hub.docker.com/r/docker/compose/tags?page=1&ordering=last_updated
