#
# ci/cloudbuild.pr.app.yaml
#
# Trigger:
#   - PR is made or changed; changes affect 'packages/app' or 'packages/app-deploy-ops'
#
# Cloud Build project:
#   - Common CI builder (not project specific; no deploys!)
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#

steps:
# Root install
#
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['install']

# --- Backend
#
# Do not care to test it - separate PR task does it.
#
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['install']
  dir: packages/backend

# --- App
#
# tbd. Once a Cypress image is available, _use it also for the install step_. This way, we don't need to deal with
#     the binaries cache.
#
# tbd. Eventually the '--headless' wouldn't be needed (Cypress is trying to make it the default for 'cypress run').
#
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['install']
  dir: packages/app
  env: ['CYPRESS_INSTALL_BINARY=0']
#- name: gcr.io/$PROJECT_ID/firebase-ci-builder-cypress:${_CYPRESS_TAG}
#  entrypoint: npm
#  args: ['install']
#  dir: packages/app
#- name: gcr.io/$PROJECT_ID/firebase-ci-builder-cypress:${_CYPRESS_TAG}
#  entrypoint: npm
#  args: ['run', 'ci:test']
#  dir: packages/app
#  env: [ 'CYPRESS_RUN_FLAGS="--browser chrome --headless"' ]
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['run', 'lint']
  dir: packages/app
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['run', 'build']
  dir: packages/app

# --- App-deploy-ops
#
# Test we can build it. Can fake the access values, because this code's not going to be run.
#
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['install']
  dir: packages/app-deploy-ops
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['run', 'ci:build']
  dir: packages/app-deploy-ops
  env: ['RAYGUN_API_KEY=abc', 'CI_JUST_BUILD=1']

# --- Timeout
#
# Local:        ...
# Cloud Build:  2:16 (without Cypress tests)
#
timeout: 240s

substitutions:
  _BUILDER_TAG: 9.16.0-node16-npm7
  #_CYPRESS_IMAGE: cypress/included:7.4.0
