#
# ci/cloudbuild.backend.deploy.yaml
#
# Triggers:
#   - new stuff is merged to a branch ('$BRANCH_NAME'); changes either in 'packages/backend/**' or root 'package.json'
#
# GCP Project:
#   Production/staging GCP project (deploys to itself).
#
# Responsibility:
#   - deploy backend
#
# Uses images:
#   - node:{16|18}-alpine (stock image)
#   - firebase-emulators  (pushed to Artifact Registry)   contains Firebase CLI we use for deployment
#   - git                 (Cloud Build built-in image)
#   - gsutil              (Cloud Build built-in image)
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Manual triggering:
#   - Provide an SHA of a tested commit by '--substitutions=_TESTED_SHA=...'.
#
# References:
#   - Cloud Build > Substituting variable values
#     -> https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
#
steps:
# Flight check
- name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args: ['-c', '
    [ $PROJECT_ID != ${_MY_BUILDER} ] || ( >&2 echo "ERROR: Please change to the deployment project: gcloud config set project <project-id>"; false ) &&
    
    if [ -z ${SHORT_SHA} ]; then
      [ ! -z ${_TESTED_SHA} ] || 
        ( >&2 echo "ERROR: For manual runs, please provide an sha of a commit that has passed the tests. ''--substitutions=_TESTED_SHA=...''"; false ) &&

      >&2 echo "** MANUAL TRIGGER **" &&
      echo ${_TESTED_SHA} > .TESTED_SHA
    ; else
      git fetch --depth=2 &&
      git rev-parse --short HEAD~1 > .TESTED_SHA
    ; fi
  ']

- name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args: ['-c', '
    export TESTED_SHA=$$( cat .TESTED_SHA ) &&    

    gsutil cat ${_GS_TOUCH_PATH}/$${TESTED_SHA} ||
      ( >&2 echo "ERROR: No evidence that tests would have passed. ''${_GS_TOUCH_PATH}/$${TESTED_SHA}'' does not exist"; false )
  ']

# Install
#
- name: node:${_NODE_VER}-alpine
  entrypoint: sh
  args: ['-c', '
    apk add --update make &&
    npm config set update-notifier false &&

    npm install &&
    npm --prefix packages/backend install &&

    (cd packages/backend &&
      make ci:deploy:firebase.json
    )
  ']

  # State:
  #   - packages/backend/functions                are installed
  #   - packages/backend/firebase.json            generated ('firebase.app.js' without the emulators)

# DEPLOY
#
- name: $_1
  entrypoint: sh
  args: ['-c', '
    firebase use $PROJECT_ID &&

    LOCATION_ID=$$(firebase apps:sdkconfig | grep -E ''^\s+"locationId":\s.+,'' | cut -d ''"'' -f4) &&
    [ ! -z $$LOCATION_ID ] || ( >&2 echo "ERROR: No ''locationId'' in Firebase app configuration (needs some tweaks)"; false ) && 
    echo "Using location id: $${LOCATION_ID}" &&
    
    cat functions/config.js | sed -E "s/import\.meta\.env\.LOCATION_ID/''$${LOCATION_ID}''/" > .a &&
      mv .a functions/config.js
  ']
    # ^-- #hack: would rather replace any occurrence of '${LOCATION_ID}' within 'functions/**.js'.
  dir: packages/backend
    #
    # Note: The dance of picking up region id, only to inject it into the Cloud Functions source, so that Firebase can
    #   again pick it up just feels wrong. Is this really the way?
    #
    # tbd. Test that it deploys to 'us-central1'.

  # State:
  #   - packages/backend/functions/config.js    modified so that 'import.meta.env.LOCATION_ID' is replaced by the target region

- name: $_1
  entrypoint: firebase
  args: ['deploy', '--only', 'functions,firestore,database']
  dir: packages/backend

  # DEBUG hint: If not deploying, add '--debug' to the params.

# --- Timeout
#
# Cloud Build: 2:21, 2:40, 3:03
#
timeout: 300s

# Note: Substitutions don't seem to get parsed recursively (would like to use '$_BUILDER_TAG' to define the image)
#
substitutions:
  _1: us-central1-docker.pkg.dev/ci-builder/builders/firebase-emulators:11.14.4
  _NODE_VER: "18"
  _GS_TOUCH_PATH: gs://ci-builder_cloudbuild/.passed.backend    # where successful tests are marked
  _MY_BUILDER: ci-builder
  _TESTED_SHA: ""
