#
# ci/cloudbuild.app.yaml
#
# Trigger:
#   - PR is made or changed; changes affect 'packages/app' or 'packages/app-deploy-ops' (or '/package.json', or 'tools/**')
#
# Cloud Build project:
#   - Common CI builder (not project specific; no deploys!)
#
# Uses images:
#   - node:16-alpine
#   - firebase-ci-builder   (pushed to Container Registry; used via Docker Compose)
#   - docker/compose
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Note:
#   Using 'node:16' to run 'npm install' means that the packages are installed as root, and 'node_modules' is read-only
#   to regular users (of other images). This is normally not a concern.

steps:
# Root install
#
- name: node:16-alpine
  entrypoint: npm
  args: ['install']

# --- Backend
#
# Do not care to test it - separate PR task does it.
#
- name: node:16-alpine
  entrypoint: npm
  args: ['install']
  dir: packages/backend

# --- App
#
- name: node:16-alpine
  entrypoint: npm
  args: ['install']
  dir: packages/app
  env: ['CYPRESS_INSTALL_BINARY=0']

# Launch emulators; keeps them running in the background.
#
# Note: Unlike in 'dev', no priming of data & users is needed. Cypress tests carry their own.
#
- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.yml', '-f', 'docker-compose.ci.yml', 'run', 'vite-launched-ci']
  dir: packages/app
  env:
    - CI_BUILDER_IMAGE=gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}
    - NODE_V=16

- name: cypress/included:${_CYPRESS_TAG}
  args: ['run', '--headless']
  dir: packages/app
  env:
    - CYPRESS_baseUrl=http://vite:3000
    - CYPRESS_defaultCommandTimeout=10000
    #
    # Tests durations:
    #   1: 7541, 7682 ms
    #   2: 3980, 4289 ms

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'lint']
  dir: packages/app

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'ci:build']
  dir: packages/app

# --- App-deploy-ops
#
# Try that the code builds with fake access values.
#
- name: node:16-alpine
  entrypoint: npm
  args: ['install']
  dir: packages/app-deploy-ops

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'ci:build:fake']
  dir: packages/app-deploy-ops
  #env: ['ENV=fake', 'RAYGUN_API_KEY=x']

# --- Timeout
#
# Cloud Build:
#   - with Cypress tests: 5:54
#   - without Cypress tests (old): 2:33, 2:13, 2:04
#
timeout: 500s

substitutions:
  _BUILDER_TAG: 9.17.0-node16-npm7
  _DOCKER_COMPOSE_TAG: 1.29.2
    # https://hub.docker.com/r/docker/compose/tags?page=1&ordering=last_updated
  _CYPRESS_TAG: 8.3.1
    # https://hub.docker.com/r/cypress/included/tags?page=1&ordering=last_updated
